on:
  push:
    paths-ignore:
      - '**/*.md'
      - '**/*.MD'   # (optional) catch uppercase
  pull_request:
    paths-ignore:
      - '**/*.md'
      - '**/*.MD'
  workflow_dispatch: {}

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
